version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    depends_on:
      - product-service
      - holiday-service

  product-service:
    build: ./product-service
    ports:
      - "5001:5001"

  holiday-service:
    build: ./holiday-service
    ports:
      - "5002:5002"
